apps/accounts/urls.py
from django.urls.conf import path, include

from apps.accounts.views import AccountListView, AccountCreateView, AccountDeleteView, AccountDetailView

urlpatterns = [
    path('', AccountListView.as_view(), name='index'),
    path('create/', AccountCreateView.as_view(success_url='/accounts/'), name='create'),
    path('view/<int:pk>/', AccountDetailView.as_view(), name='view'),
    path('delete/<int:pk>/', AccountDeleteView.as_view(success_url='/accounts/'), name='delete'),
    path('ajax/', include(('apps.accounts.ajax_urls', 'ajax'))),
]

apps/home/urls.py
from django.urls import path

from apps.home.views import IndexView, LoginView, LogoutView

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

apps/transactions/urls.py
from django.urls.conf import path

from apps.transactions.views import ListView

urlpatterns = [
    path('', ListView.as_view(), name='index'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include(('apps.home.urls', 'home'))),
    path('accounts/', include(('apps.accounts.urls', 'accounts'))),
    path('transactions/', include(('apps.transactions.urls', 'transactions'))),
    path('admin/', admin.site.urls),
]

apps/accounts/models.py
from django.contrib.auth.models import User
from django.db import models


class Currency(models.Model):
    title = models.CharField(max_length=255, null=False, blank=False)
    iso4217 = models.CharField(max_length=3, null=False, blank=False, unique=True)
    created_at = models.DateTimeField(null=False, blank=True, editable=False)
    updated_at = models.DateTimeField(default=None, null=True, blank=True, editable=False)

    def __str__(self):
        return '%s (%s)' % (self.title, self.iso4217)


class Account(models.Model):
    title = models.CharField(max_length=255, null=False, blank=False)
    description = models.TextField(default=None, null=True, blank=True)
    amount = models.DecimalField(max_digits=15, decimal_places=2, null=False, blank=True, default=0.0, editable=False)
    user = models.ForeignKey(User, related_name='accounts', db_column='user_id', null=False, blank=False, on_delete=models.CASCADE)
    currency = models.ForeignKey(Currency, db_column='currency_id', null=False, blank=False, on_delete=models.PROTECT)
    created_at = models.DateTimeField(null=False, blank=True, editable=False)
    updated_at = models.DateTimeField(default=None, null=True, blank=True, editable=False)

    def __str__(self):
        return '%s (%s)' % (self.title, self.amount)

apps/transactions/models.py
from django.contrib.auth.models import User
from django.db import models

from apps.accounts.models import Account
from apps.db.fields import TransactionTypeField


class Category(models.Model):
    type = TransactionTypeField(null=False, blank=False)
    title = models.CharField(max_length=255, null=False, blank=False)
    description = models.TextField(default=None, null=True, blank=True)
    user = models.ForeignKey(User, null=False, blank=False, db_column='user_id', on_delete=models.CASCADE)
    created_at = models.DateTimeField(null=False, blank=True, editable=False)
    updated_at = models.DateTimeField(default=None, null=True, blank=True, editable=False)

    def __str__(self):
        return self.title


class Transaction(models.Model):
    type = TransactionTypeField(null=False, blank=False)
    amount = models.DecimalField(max_digits=15, decimal_places=2, null=False, blank=False)
    category = models.ForeignKey(Category, null=False, blank=False, db_column='category_id', on_delete=models.PROTECT)
    account = models.ForeignKey(Account, null=False, blank=False, db_column='account_id', on_delete=models.CASCADE)
    created_at = models.DateTimeField(null=False, blank=True, editable=False)
    updated_at = models.DateTimeField(default=None, null=True, blank=True, editable=False)

    def __str__(self):
        return '%s (%f)' % (self.category.title, self.amount)

apps/accounts/views.py
import json

from django.http import HttpResponse
from django.views import View
from django.views.generic import ListView, CreateView, DeleteView, DetailView

from apps.accounts.models import Account, Currency


class AccountListView(ListView):
    template_name = 'accounts/index.html'
    queryset = Account.objects

    def get_queryset(self):
        queryset = super(AccountListView, self).get_queryset()
        queryset = queryset.filter(user__exact=self.request.user)

        return queryset.all()


class AccountDetailView(DetailView):
    template_name = 'accounts/view.html'
    queryset = Account.objects

    def get_queryset(self):
        queryset = super(AccountDetailView, self).get_queryset()
        queryset = queryset.filter(user__exact=self.request.user)

        return queryset.all()


class AccountCreateView(CreateView):
    template_name = 'accounts/create.html'
    model = Account
    fields = ('title', 'description', 'currency')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(AccountCreateView, self).form_valid(form)


class AccountDeleteView(DeleteView):
    queryset = Account.objects

    def get_queryset(self):
        queryset = super(AccountDeleteView, self).get_queryset()
        queryset = queryset.filter(user__exact=self.request.user)

        return queryset.all()

    def get(self, request, *args, **kwargs):
        return self.delete(request, *args, **kwargs)


class CurrencyAjaxListView(View):
    def get(self, request):
        queryset = Currency.objects.order_by('title')

        term = request.GET.get('term', None)
        if term is not None:
            queryset = queryset.filter(title__istartswith=term)

        currencies = queryset.all()
        data = {'results': [], 'pagination': {'more': False}}

        for currency in currencies:
            data['results'].append({
                'id': currency.pk,
                'text': currency.title,
            })

        return HttpResponse(
            json.dumps(data),
            content_type='application/json'
        )

apps/home/views.py
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView
from django.contrib.auth.views import LoginView as BaseLoginView, LogoutView as BaseLogoutView

from apps.home.decorators import anonymous_required


@method_decorator(login_required, name='dispatch')
class IndexView(TemplateView):
    template_name = 'home/index.html'


@method_decorator(anonymous_required, name='dispatch')
class LoginView(BaseLoginView):
    template_name = 'home/login.html'


@method_decorator(login_required, name='dispatch')
class LogoutView(BaseLogoutView):
    next_page = '/login/'

apps/transactions/views.py
from django.views.generic import ListView as BaseListView

from apps.transactions.models import Transaction


class ListView(BaseListView):
    template_name = 'transactions/index.html'
    queryset = Transaction.objects

    def get_queryset(self):
        queryset = super(ListView, self).get_queryset()
        queryset.filter(account__user__exact=self.request.user)

        return queryset.all()

templates/accounts/create.html
{% extends 'layouts/gentelella/layout.html' %}
{% load staticfiles %}

{% block head %}

    {{ block.super }}

    <link rel="stylesheet" type="text/css" href="{% static 'select2/dist/css/select2.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'select2-bootstrap-theme/dist/select2-bootstrap.min.css' %}">

{% endblock %}

{% block content_header %}

    <div class="page-title">
        <div class="title_left">
            <h3>Accounts</h3>
        </div>
    </div>

{% endblock %}

{% block content %}

    <div class="x_panel">
        <div class="x_content">

            <form id="demo-form2" data-parsley-validate class="form-horizontal form-label-left" method="post">

                {% csrf_token %}

                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12"
                           for="{{ form.title.id_for_label }}">{{ form.title.label }} <span
                            class="required">*</span>
                    </label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        <input type="text" id="{{ form.title.id_for_label }}" required="required"
                               class="form-control col-md-7 col-xs-12" name="{{ form.title.name }}"
                               value="{{ form.title.value | default_if_none:'' }}">
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12"
                           for="{{ form.description.id_for_label }}">{{ form.description.label }}
                    </label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        <textarea class="form-control col-md-7 col-xs-12" name="{{ form.description.name }}"
                                  id="{{ form.description.id_for_label }}">{{ form.description.value|default_if_none:'' }}</textarea>
                    </div>
                </div>
                <div class="form-group">
                    <label for="{{ form.currency.id_for_label }}"
                           class="control-label col-md-3 col-sm-3 col-xs-12">{{ form.currency.label }}</label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        <select name="{{ form.currency.name }}" class="form-control col-md-7 col-xs-12"
                                id="{{ form.currency.id_for_label }}">
                            <option value="">Select currency ...</option>
                        </select>
                    </div>
                </div>
                <div class="ln_solid"></div>
                <div class="form-group">
                    <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                        <button type="submit" class="btn btn-success">Submit</button>
                    </div>
                </div>

            </form>
        </div>
    </div>

{% endblock %}

{% block body_end %}

    {{ block.super }}

    <script type="text/javascript" src="{% static 'select2/dist/js/select2.js' %}"></script>
    <script type="text/javascript">

        $(function () {
            $('#{{ form.currency.id_for_label }}').select2({
                theme: 'bootstrap',
                ajax: {
                    url: '{% url 'accounts:ajax:currency' %}',
                    dataType: 'json'
                }
            });

        });

    </script>

{% endblock %}

templates/accounts/index.html
{% extends 'layouts/gentelella/layout.html' %}

{% block content_header %}

    <div class="page-title">
        <div class="title_left">
            <h3>Accounts</h3>
        </div>
    </div>

{% endblock %}

{% block content %}

    <div class="x_panel">
        <div class="x_content">

            <a href="{% url 'accounts:create' %}" class="btn btn-success">Create</a>

            <div class="clearfix"></div>

            <table class="table">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Title</th>
                    <th>Amount</th>
                    <th>Currency</th>
                    <th>Actions</th>
                </tr>
                </thead>
                <tbody>

                {% for account in account_list %}
                    <tr class="text-{% if account.amount >= 0 %}success{% else %}danger{% endif %}">
                        <td>{{ account.id }}</td>
                        <td>{{ account.title }}</td>
                        <td>{{ account.amount }}</td>
                        <td>{{ account.currency.iso4217 }}</td>
                        <td>
                            <a href="{% url 'accounts:view' account.id %}" class="btn btn-primary">
                                <i class="fa fa-eye"></i>
                            </a>
                            <a href="{% url 'accounts:delete' account.id %}" class="btn btn-danger">
                                <i class="fa fa-trash"></i>
                            </a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

        </div>
    </div>

{% endblock %}

templates/accounts/view.html
{% extends 'layouts/gentelella/layout.html' %}

{% block content_header %}

    <div class="page-title">
        <div class="title_left">
            <h3>Accounts
                <small>{{ account.title }} detail</small>
            </h3>
        </div>
    </div>

{% endblock %}

{% block content %}

    <div class="row">

        <div class="col-sm-4 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>Account Info</h2>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <table class="table table-bordered">
                        <tr>
                            <th>ID</th>
                            <td>{{ account.id }}</td>
                        </tr>
                        <tr>
                            <th>Title</th>
                            <td>{{ account.title }}</td>
                        </tr>
                        <tr>
                            <th>Description</th>
                            <td>{{ account.description }}</td>
                        </tr>
                        <tr>
                            <th>Currency</th>
                            <td>{{ account.currency.title }}</td>
                        </tr>
                        <tr>
                            <th>Amount</th>
                            <td class="text-{% if account.amount >= 0 %}success{% else %}danger{% endif %}">
                                {{ account.amount }}
                            </td>
                        </tr>
                    </table>
                </div>
            </div>

        </div>

        <div class="col-sm-8 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>Transactions</h2>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <table class="table">
                        <thead>
                        <tr>
                            <th>Created At</th>
                            <th>Type</th>
                            <th>Amount</th>
                            <th>Currency</th>
                            <th>Category</th>
                        </tr>
                        </thead>
                        <tbody>

                        {% for transaction in account.transaction_set.all %}
                            <tr>
                                <td>{{ transaction.created_at|date }} {{ transaction.created_at|time }}</td>
                                <td>
                                    {% if transaction.type == 'I' %}
                                        <i class="fa fa-arrow-up text-success"></i>
                                    {% else %}
                                        <i class="fa fa-arrow-down text-danger"></i>
                                    {% endif %}
                                </td>
                                <td class="text-{% if transaction.type == 'I' %}success{% else %}danger{% endif %}">{{ transaction.amount }}</td>
                                <td>{{ transaction.account.currency.iso4217 }}</td>
                                <td>{{ transaction.category.title }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

    </div>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>

    {% block head %}{% endblock %}

</head>
<body{% block body_attrs %}{% endblock %}>

    {% block body %}{% endblock %}

    {% block body_end %}{% endblock %}

</body>
</html>

templates/home/index.html
{% extends 'layouts/gentelella/layout.html' %}

{% block content_header %}

    <div class="page-title">
        <div class="title_left">
            <h3>Home</h3>
        </div>
    </div>

{% endblock %}

{% block content %}

    Home page.

{% endblock %}

templates/home/login.html
{% extends 'layouts/gentelella/layout.html' %}

{% block body_attrs %} class="login"{% endblock %}

{% block body %}

    <div>
        <div class="login_wrapper">
            <div class="animate form login_form">
                <section class="login_content">
                    <form method="post">
                        <h1>Login Form</h1>

                        {% csrf_token %}

                        {{ form.non_field_errors }}

                        <div>
                            {{ form.username.errors }}
                            <input
                                type="text"
                                class="form-control"
                                placeholder="{{ form.username.label }}"
                                name="{{ form.username.name }}"
                                value="{{ form.username.value | default_if_none:'' }}"
                                required
                            />
                        </div>
                        <div>
                            {{ form.password.errors }}
                            <input
                                type="password"
                                class="form-control"
                                placeholder="Password"
                                name="{{ form.password.name }}"
                                value="{{ form.password.value | default_if_none:'' }}"
                                required
                            />
                        </div>
                        <div>
                            <button class="btn btn-default submit" type="submit">Log in</button>
                        </div>

                        <div class="clearfix"></div>
                    </form>
                </section>
            </div>
        </div>
    </div>

{% endblock %}

templates/layouts/base/layout.html
<!DOCTYPE html>
<html lang="en">
<head>

    {% block head %}{% endblock %}

</head>
<body{% block body_attrs %}{% endblock %}>

    {% block body %}{% endblock %}

    {% block body_end %}{% endblock %}

</body>
</html>

templates/layouts/gentelella/_bottom.html
<footer>
    <div class="pull-right">
        Budget Assistant &copy;{% now 'Y' %}
    </div>
    <div class="clearfix"></div>
</footer>

templates/layouts/gentelella/_left.html
{% load staticfiles %}

<div class="col-md-3 left_col">
    <div class="left_col scroll-view">
        <div class="navbar nav_title" style="border: 0;">
            <a href="/" class="site_title"><i class="fa fa-money"></i> <span>Budget Assistant</span></a>
        </div>

        <div class="clearfix"></div>

        <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
            <div class="menu_section">
                <ul class="nav side-menu">
                    <li><a href="/">
                        <i class="fa fa-home"></i> Home
                    </a></li>
                    <li><a href="{% url 'accounts:index' %}">
                        <i class="fa fa-circle-o"></i> Accounts
                    </a></li>
                    <li><a href="{% url 'transactions:index' %}">
                        <i class="fa fa-circle-o"></i> Transactions
                    </a></li>
                </ul>
            </div>
        </div>
    </div>
</div>

templates/layouts/gentelella/_top.html
{% load staticfiles %}

<div class="top_nav">
    <div class="nav_menu">
        <nav>
            <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
            </div>

            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                        {{ user.username }}
                        <span class=" fa fa-angle-down"></span>
                    </a>
                    <ul class="dropdown-menu dropdown-usermenu pull-right">
                        <li><a href="{% url 'home:logout' %}"><i class="fa fa-sign-out pull-right"></i> Log Out</a></li>
                    </ul>
                </li>
            </ul>
        </nav>
    </div>
</div>

templates/layouts/gentelella/layout.html
{% extends 'layouts/base/layout.html' %}
{% load staticfiles %}

{% block head %}

    {{ block.super }}

    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Gentelella Alela! | </title>

    <!-- Bootstrap -->
    <link href="{% static 'gentelella/vendors/bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="{% static 'gentelella/vendors/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
    <!-- NProgress -->
    <link href="{% static 'gentelella/vendors/nprogress/nprogress.css' %}" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="{% static 'gentelella/build/css/custom.min.css' %}" rel="stylesheet">

{% endblock %}

{% block body_attrs %} class="nav-md"{% endblock %}

{% block body %}

    <div class="container body">
        <div class="main_container">

            {% include 'layouts/gentelella/_left.html' %}

            {% include 'layouts/gentelella/_top.html' %}

            <div class="right_col" role="main">
                <div class="">
                    {% block content_header %}
                        <div class="page-title">
                            <div class="title_left">
                                <h3>Plain Page</h3>
                            </div>
                        </div>
                    {% endblock %}

                    <div class="clearfix"></div>

                    {% block content %}
                        <div class="row">
                            <div class="col-md-12 col-sm-12 col-xs-12">
                                <div class="x_panel">
                                    <div class="x_title">
                                        <h2>Plain Page</h2>
                                        <ul class="nav navbar-right panel_toolbox">
                                            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                            </li>
                                            <li class="dropdown">
                                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                                                   aria-expanded="false"><i class="fa fa-wrench"></i></a>
                                                <ul class="dropdown-menu" role="menu">
                                                    <li><a href="#">Settings 1</a>
                                                    </li>
                                                    <li><a href="#">Settings 2</a>
                                                    </li>
                                                </ul>
                                            </li>
                                            <li><a class="close-link"><i class="fa fa-close"></i></a>
                                            </li>
                                        </ul>
                                        <div class="clearfix"></div>
                                    </div>
                                    <div class="x_content">
                                        Add content to the page ...
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endblock %}
                </div>
            </div>

            {% include 'layouts/gentelella/_bottom.html' %}
        </div>
    </div>

{% endblock %}

{% block body_end %}

    <!-- jQuery -->
    <script src="{% static 'gentelella/vendors/jquery/dist/jquery.min.js' %}"></script>
    <!-- Bootstrap -->
    <script src="{% static 'gentelella/vendors/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <!-- FastClick -->
    <script src="{% static 'gentelella/vendors/fastclick/lib/fastclick.js' %}"></script>
    <!-- NProgress -->
    <script src="{% static 'gentelella/vendors/nprogress/nprogress.js' %}"></script>

    <!-- Custom Theme Scripts -->
    <script src="{% static 'gentelella/build/js/custom.min.js' %}"></script>

{% endblock %}

templates/transactions/index.html
{% extends 'layouts/gentelella/layout.html' %}

{% block content_header %}

    <div class="page-title">
        <div class="title_left">
            <h3>Transactions</h3>
        </div>
    </div>

{% endblock %}

{% block content %}

    <div class="x_panel">
        <div class="x_content">

            <table class="table">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Account</th>
                    <th>Type</th>
                    <th>Amount</th>
                    <th>Currency</th>
                    <th>Category</th>
                </tr>
                </thead>
                <tbody>

                {% for transaction in transaction_list %}
                    <tr>
                        <td>{{ transaction.id }}</td>
                        <td>{{ transaction.account.title }}</td>
                        <td>
                            {% if transaction.type == 'I' %}
                                <i class="fa fa-arrow-up text-success"></i>
                            {% else %}
                                <i class="fa fa-arrow-down text-danger"></i>
                            {% endif %}
                        </td>
                        <td class="text-{% if transaction.type == 'I' %}success{% else %}danger{% endif %}">{{ transaction.amount }}</td>
                        <td>{{ transaction.account.currency.iso4217 }}</td>
                        <td>{{ transaction.category.title }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

        </div>
    </div>

{% endblock %}